### ISSUE TITLE
README Issue: There is no calendar image in this project.

### ISSUE THREAD

**Issue by luiscmartinez** [Onye-PRS/react-Next.js-interview#1]
The read me states the following: ⬇️

> The Task You should start by rendering a single month view of a calendar for the current month – along with the lines of the calendar image in this project.

There is no image file in this repo.

**Comment by etiosa** [comment]
![calendar](https://user-images.githubusercontent.com/6495636/181367427-d7883da7-4583-4788-bdcf-b23e05a39459.png)
 I have attached the file. Sorry about that

**Comment by luiscmartinez** [comment]
@etiosa Thank you 👍
